#!/bin/bash

# This file is automatically generated by the DockerFileBuildHelper tool, run DockerFileBuildHelper/update-repo.sh to update it
set -e
# Build docker-compose-generator
git clone https://github.com/btcpayserver/btcpayserver-docker docker-compose-generator
cd docker-compose-generator
git checkout dcg-latest
cd docker-compose-generator
docker build -f "linuxamd64.Dockerfile" -t "btcpayserver/docker-compose-generator:latest" .
cd - && cd ..


# Build docker-compose-builder
git clone https://github.com/btcpayserver/docker-compose-builder docker-compose-builder
cd docker-compose-builder
git checkout v1.23.2
cd .
docker build -f "linuxarm32v7.Dockerfile" -t "btcpayserver/docker-compose-builder:1.23.2" .
cd - && cd ..


# Build btglnd
git clone https://github.com/vutov/lnd btglnd
cd btglnd
git checkout master
cd .
docker build -f "BTCPayServer.Dockerfile" -t "kamigawabul/btglnd:latest" .
cd - && cd ..


# Build docker-bitcoingold
git clone https://github.com/Vutov/docker-bitcoin docker-bitcoingold
cd docker-bitcoingold
git checkout master
cd bitcoingold/0.15.2
docker build -f "Dockerfile" -t "kamigawabul/docker-bitcoingold:0.15.2" .
cd - && cd ..


# Build clightning
git clone https://github.com/NicolasDorier/lightning clightning
cd clightning
git checkout basedon-v0.6.2-3
cd .
docker build -f "Dockerfile" -t "nicolasdorier/clightning:v0.6.2-3" .
cd - && cd ..


# Build lnd
git clone https://github.com/btcpayserver/lnd lnd
cd lnd
git checkout basedon-v0.5-beta-2
cd .
docker build -f "BTCPayServer.Dockerfile" -t "btcpayserver/lnd:0.5-beta-2" .
cd - && cd ..


# Build bitcoin
git clone https://github.com/btcpayserver/dockerfile-deps bitcoin
cd bitcoin
git checkout Bitcoin/0.17.0
cd Bitcoin/0.17.0
docker build -f "linuxamd64.Dockerfile" -t "btcpayserver/bitcoin:0.17.0" .
cd - && cd ..


# Build btcpayserver
git clone https://github.com/btcpayserver/btcpayserver btcpayserver
cd btcpayserver
git checkout v1.0.3.21
cd .
docker build -f "Dockerfile.linuxamd64" -t "btcpayserver/btcpayserver:1.0.3.21" .
cd - && cd ..


# Build dogecoin
git clone https://github.com/rockstardev/docker-bitcoin dogecoin
cd dogecoin
git checkout feature/dogecoin
cd dogecoin/1.10.0
docker build -f "Dockerfile" -t "rockstardev/dogecoin:1.10.0" .
cd - && cd ..


# Build docker-feathercoin
git clone https://github.com/ChekaZ/docker docker-feathercoin
cd docker-feathercoin
git checkout master
cd feathercoin/0.16.3
docker build -f "Dockerfile" -t "chekaz/docker-feathercoin:0.16.3" .
cd - && cd ..


# Build docker-groestlcoin
git clone https://github.com/NicolasDorier/docker-bitcoin docker-groestlcoin
cd docker-groestlcoin
git checkout master
cd groestlcoin/2.16.3
docker build -f "Dockerfile" -t "nicolasdorier/docker-groestlcoin:2.16.3" .
cd - && cd ..


# Build clightning
git clone https://github.com/NicolasDorier/lightning clightning
cd clightning
git checkout basedon-v0.6.2-3
cd .
docker build -f "Dockerfile" -t "nicolasdorier/clightning:v0.6.2-3" .
cd - && cd ..


# Build lnd
git clone https://github.com/btcpayserver/lnd lnd
cd lnd
git checkout basedon-v0.5-beta-2
cd .
docker build -f "BTCPayServer.Dockerfile" -t "btcpayserver/lnd:0.5-beta-2" .
cd - && cd ..


# Build docker-litecoin
git clone https://github.com/NicolasDorier/docker-bitcoin docker-litecoin
cd docker-litecoin
git checkout master
cd litecoin/0.16.3
docker build -f "Dockerfile" -t "nicolasdorier/docker-litecoin:0.16.3" .
cd - && cd ..


# Build docker-monacoin
git clone https://github.com/wakiyamap/docker-bitcoin docker-monacoin
cd docker-monacoin
git checkout master
cd monacoin/0.16.3
docker build -f "Dockerfile" -t "wakiyamap/docker-monacoin:0.16.3" .
cd - && cd ..


# Build nbxplorer
git clone https://github.com/dgarage/nbxplorer nbxplorer
cd nbxplorer
git checkout v2.0.0.1
cd .
docker build -f "Dockerfile.linuxamd64" -t "nicolasdorier/nbxplorer:2.0.0.1" .
cd - && cd ..


# Build nginx
git clone https://github.com/nginxinc/docker-nginx nginx
cd nginx
git checkout master
cd stable/stretch
docker build -f "Dockerfile" -t "nginx:stable" .
cd - && cd ..


# Build docker-gen
git clone https://github.com/btcpayserver/docker-gen docker-gen
cd docker-gen
git checkout v0.7.4
cd .
docker build -f "linuxamd64.Dockerfile" -t "btcpayserver/docker-gen:0.7.4" .
cd - && cd ..


# Build letsencrypt-nginx-proxy-companion
git clone https://github.com/btcpayserver/docker-letsencrypt-nginx-proxy-companion letsencrypt-nginx-proxy-companion
cd letsencrypt-nginx-proxy-companion
git checkout v1.10.0
cd .
docker build -f "linuxamd64.Dockerfile" -t "btcpayserver/letsencrypt-nginx-proxy-companion:1.10.0" .
cd - && cd ..


# Build postgres
git clone https://github.com/docker-library/postgres postgres
cd postgres
git checkout b7cb3c6eacea93be2259381033be3cc435649369
cd 9.6
docker build -f "Dockerfile" -t "postgres:9.6.5" .
cd - && cd ..


# Build traefik
git clone https://github.com/containous/traefik-library-image traefik
cd traefik
git checkout master
cd scratch/amd64
docker build -f "Dockerfile" -t "traefik:latest" .
cd - && cd ..


# Build docker-viacoin
git clone https://github.com/viacoin/docker-viacoin docker-viacoin
cd docker-viacoin
git checkout master
cd viacoin/0.15.2
docker build -f "docker-viacoin" -t "romanornr/docker-viacoin:0.15.2" .
cd - && cd ..


