version: "3"
# If you don't use Lightning Network, use opt-save-store-xxs instead
# This save about 3 months of block, your lightning node won't be able to see channel created 3 months since the time you start it.

services:
  bitcoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=25000
  bitcored:
    environment:
      BITCOIN_EXTRA_ARGS: prune=25000
  bgoldd:
    environment:
      BITCOIN_EXTRA_ARGS: prune=25000
  feathercoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=25000
  groestlcoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=25000
  litecoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=25000
  viacoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=25000
  dogecoind:
    environment:
      DOGECOIN_EXTRA_ARGS: prune=25000
  monacoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=25000
exclusive:
  - pruning
