services:
  cloudflared:
    container_name: 'cloudflared-tunnel'
    image: btcpayserver/cloudflared:2026.9.3
    command: 'tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}'
    restart: 'on-failure'
    environment:
      REAL_IP_HEADER: Cf-Connecting-Ip
    links:
      - nginx
  nginx-gen:
    environment:
      - TRUST_DOWNSTREAM_PROXY=true

required:
  - "nginx"
excluded:
  - "nginx-https"
