version: "3"
# If you don't use Lightning Network, use opt-save-store-xxs instead
# This save about 6 months of block, your lightning node won't be able to see channel created 6 months since the time you start it.

services:
  bitcoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=50000
  bitcored:
    environment:
      BITCOIN_EXTRA_ARGS: prune=50000
  bgoldd:
    environment:
      BITCOIN_EXTRA_ARGS: prune=50000
  feathercoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=50000
  groestlcoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=50000
  litecoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=50000
  viacoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=50000
  dogecoind:
    environment:
      DOGECOIN_EXTRA_ARGS: prune=50000
  monacoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=50000
exclusive:
  - pruning
