version: "3"
# If your machine has moar than 1GB of memory dedicated for bitcoind, use this

services:
  bitcoind:
    environment:
      BITCOIN_EXTRA_ARGS: |
        dbcache=1024
  bgoldd:
    environment:
      BITCOIN_EXTRA_ARGS: |
        dbcache=1024
  feathercoind:
    environment:
      BITCOIN_EXTRA_ARGS: |
        dbcache=1024
  groestlcoind:
    environment:
      BITCOIN_EXTRA_ARGS: |
        dbcache=1024
  litecoind:
    environment:
      BITCOIN_EXTRA_ARGS: |
        dbcache=1024
  viacoind:
    environment:
      BITCOIN_EXTRA_ARGS: |
        dbcache=1024
  monacoind:
    environment:
      BITCOIN_EXTRA_ARGS: |
        dbcache=1024
  elementsd_liquid:
    environment:
      ELEMENTS_EXTRA_ARGS: |
        dbcache=1024
exclusive:
  - memory
