version: "3"

services:
  bitcoind:
    environment:
      BITCOIN_EXTRA_ARGS: |
        rpcauth=electrumx:7d8ee47c089e6072635f82b34796e878$$13649d99453ccdf78e85007286422599c00e6953289f41bf8e92961076ba14db
  fulcrum:
    image: cculianu/fulcrum:v1.9.3
    restart: unless-stopped
    expose:
      - "50001"
    ports:
      - "50002:50002"
    volumes:
      - "fulcrum_datadir:/data"
    command: "Fulcrum -b bitcoind:43782 -t 0.0.0.0:50001 -s 0.0.0.0:50002 -u electrumx -p 1VmSUVGBuLNWvZl0LExRDW0tvl6196-47RfXIzS384g="
volumes:
  fulcrum_datadir:
incompatible:
  - pruning
required:
  - "opt-txindex"
