services:
  btcpayserver:
    volumes:
      - "lnd_lit_datadir:/lit:ro"
  lnd_bitcoin:
    environment:
      LND_EXTRA_ARGS: |
        rpcmiddleware.enable=true
  lnd_lit:
    image: "lightninglabs/lightning-terminal:v0.17.6"
    container_name: btcpayserver_litd
    restart: unless-stopped
    environment:
      LIT_AUTO_MIGRATE_TO_SQL: "true"
    expose:
      - "8443"
    volumes:
      - "lnd_lit_datadir:/lit"
      - "lnd_bitcoin_datadir:/data/lnd:ro"
    links:
      - lnd_bitcoin
    command:
      - "--disableui"
      - "--lit-dir=/lit/.lit"
      - "--loop.loopdir=/lit/.loop"
      - "--pool.basedir=/lit/.pool"
      - "--faraday.faradaydir=/lit/.faraday"
      - "--taproot-assets.tapddir=/lit/.tapd"
      - "--httpslisten=0.0.0.0:8443"
      - "--network=${NBITCOIN_NETWORK}"
      - "--lnd-mode=remote"
      - "--remote.lnd.rpcserver=lnd_bitcoin:10009"
      - "--remote.lnd.macaroonpath=/data/lnd/admin.macaroon"
      - "--remote.lnd.tlscertpath=/data/lnd/tls.cert"

volumes:
  lnd_lit_datadir:

required:
  - "bitcoin-lnd"
