version: "3"
# If you don't use Lightning Network, you want this
# This save about 2 weeks worth of block

services:
  bitcoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=5000
  bitcored:
    environment:
      BITCOIN_EXTRA_ARGS: prune=5000
  bgoldd:
    environment:
      BITCOIN_EXTRA_ARGS: prune=5000
  feathercoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=5000
  groestlcoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=5000
  litecoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=5000
  viacoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=5000
  dogecoind:
    environment:
      DOGECOIN_EXTRA_ARGS: prune=5000
  monacoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=5000
exclusive:
  - pruning
