services:
  phoenixd:
    image: acinq/phoenixd:0.9.1
    container_name: phoenixd
    restart: unless-stopped
    networks:
      - default
    command: [
      "--chain=${NBITCOIN_NETWORK:-regtest}",
      "--http-password-file=/run/secrets/phoenixd_password.pwd"
    ]
    expose:
      - "9740"
    volumes:
      - "phoenixd_datadir:/phoenix/.phoenix"
    secrets:
      - source: phoenixd_password
        target: phoenixd_password.pwd

  btcpayserver:
    environment:
      BTCPAY_BTCLIGHTNING: "type=phoenixd;server=http://phoenixd:9740;passwordfilepath=/run/secrets/phoenixd_password.pwd"
    secrets:
      - source: phoenixd_password
        target: phoenixd_password.pwd
    links:
      - phoenixd

volumes:
  phoenixd_datadir:

secrets:
  phoenixd_password:
    file: ../secrets/phoenixd_password.pwd

exclusive:
  - lightning
