version: "3"

services:
  traefik:
    restart: unless-stopped
    image: traefik:v2.6
    container_name: traefik
    ports:
      - "${REVERSEPROXY_HTTP_PORT:-80}:80"
      - "${REVERSEPROXY_HTTPS_PORT:-443}:443"
      - "8080:8080" # Dashboard, enable for debug only
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "../Traefik/traefik.yml:/traefik.yml"
      - "traefik_data:/data"
volumes:
  traefik_data:

exclusive:
  - proxy
required:
  - "traefik"
