version: "3"

services:
  traefik:
    restart: unless-stopped
    image: traefik
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.toml:/traefik.toml"
      - "./acme.json:/acme.json:ro"
      - "./servers.toml:/servers.toml"
      - "./traefik_logs:/traefik_logs"
      
    links:
      - btcpayserver

volumes:
  traefik_logs: