location /bluewallet_lndhub_app/ {
	set $btcpay_route_upstream bluewallet_lndhub_app;
	rewrite ^/bluewallet_lndhub_app/(.*)$ /$1 break;
	proxy_pass http://$btcpay_route_upstream:3000;
	proxy_redirect ~^http://bluewallet_lndhub_app:3000/?(.*)$ /bluewallet_lndhub_app/$1;
	sub_filter 'href="../' 'href="/bluewallet_lndhub_app/';
	sub_filter 'src="/' 'src="/bluewallet_lndhub_app/';
	sub_filter_once off;
}
