location /btcqbo/ {
	set $btcpay_route_upstream btcqbo;
	proxy_pass http://$btcpay_route_upstream:8001;
	proxy_redirect off;
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
