location /clightning-rest/btc/ {
	set $btcpay_route_upstream clightning_bitcoin;
	rewrite ^/clightning-rest/btc/(.*) /$1 break;
	proxy_pass http://$btcpay_route_upstream:3010;
	proxy_redirect ~^http://clightning_bitcoin:3010/?(.*)$ /clightning-rest/btc/$1;
}
