location /spark/grs/ {
	set $btcpay_route_upstream clightning_groestlcoin_spark;
	rewrite ^/spark/grs/(.*)$ /$1 break;
	proxy_pass http://$btcpay_route_upstream:9739;
	proxy_redirect ~^http://clightning_groestlcoin_spark:9739/?(.*)$ /spark/grs/$1;
}
