location /lightning-charge/grs/ {
	set $btcpay_route_upstream clightning_groestlcoin_charge;
	rewrite ^/lightning-charge/grs/(.*)$ /$1 break;
	proxy_pass http://$btcpay_route_upstream:9112;
	proxy_redirect ~^http://clightning_groestlcoin_charge:9112/?(.*)$ /lightning-charge/grs/$1;
}
