location /helipad/ {
	set $btcpay_route_upstream helipad;
	rewrite ^/helipad/(.*)$ /$1 break;
	sub_filter_once off;
	sub_filter_types *;
	sub_filter 'src="/' 'src="/helipad/';
	sub_filter 'href="/' 'href="/helipad/';
	sub_filter '/image' '/helipad/image';
	sub_filter '/pew' '/helipad/pew';
	sub_filter '/boosts' '/helipad/boosts';
	sub_filter '/api/v1/helipad' '/helipad/api/v1/helipad';
	proxy_pass http://$btcpay_route_upstream:2112;
	proxy_redirect ~^http://helipad:2112/?(.*)$ /helipad/$1;
}
