location /lit/ {
	set $btcpay_route_upstream lnd_lit;
	rewrite ^/lit/(.*)$ /$1 break;
	proxy_pass http://$btcpay_route_upstream:8080;
	proxy_redirect ~^http://lnd_lit:8080/?(.*)$ /lit/$1;
}

# LND's wallet unlocker methods are not protected by macaroons. Return 500 to
# mimic ChangePassword after a wallet is open, and avoid logging bot traffic.
location ~* ^/lnrpc\.WalletUnlocker/(GenSeed|InitWallet|UnlockWallet|ChangePassword)$ {
	access_log off;
	return 500;
}

location ~* ^/(ln|loop|pool|lit)rpc\. {
	set $btcpay_route_upstream lnd_lit;
	proxy_pass http://$btcpay_route_upstream:8080;
	proxy_redirect ~^http://lnd_lit:8080(/.*)$ $1;
}
