location /lightning-charge/btc/ {
	set $btcpay_route_upstream clightning_bitcoin_charge;
	rewrite ^/lightning-charge/btc/(.*)$ /$1 break;
	proxy_pass http://$btcpay_route_upstream:9112;
	proxy_redirect ~^http://clightning_bitcoin_charge:9112/?(.*)$ /lightning-charge/btc/$1;
}
