# LND's wallet unlocker methods are not protected by macaroons. Return 500 to
# mimic ChangePassword after a wallet is open, and avoid logging bot traffic.
location ~* ^/lnd-rest/btc/v1/(genseed|initwallet|unlockwallet|changepassword)$ {
	access_log off;
	return 500;
}

location /lnd-rest/btc/ {
	set $btcpay_route_upstream lnd_bitcoin;
	rewrite ^/lnd-rest/btc/(.*) /$1 break;
	proxy_pass http://$btcpay_route_upstream:8080;
	proxy_redirect ~^http://lnd_bitcoin:8080/?(.*)$ /lnd-rest/btc/$1;
}
