# LND's wallet unlocker methods are not protected by macaroons. Return 500 to
# mimic ChangePassword after a wallet is open, and avoid logging bot traffic.
location ~* ^/lnrpc\.WalletUnlocker/(GenSeed|InitWallet|UnlockWallet|ChangePassword)$ {
	access_log off;
	return 500;
}

location ~* ^/(lnrpc|routerrpc|verrpc|walletrpc)\. {
	set $btcpay_route_upstream lnd_bitcoin;
	grpc_read_timeout 6000s;
	grpc_send_timeout 6000s;
	grpc_pass grpcs://$btcpay_route_upstream:10009;
}
