# https://github.com/mempool/mempool/tree/master/production/nginx
location /mempool/ {
	set $btcpay_route_upstream mempool_web;
	rewrite ^/mempool/(.*)$ /$1 break;
	proxy_pass http://$btcpay_route_upstream:8080;
	proxy_redirect ~^http://mempool_web:8080/?(.*)$ /mempool/$1;

	# Bypass gzip so sub_filter can process the response.
	proxy_set_header Accept-Encoding "";
	sub_filter_types *;
	sub_filter_once off;
	sub_filter 'base href="/' 'base href="/mempool/';
	sub_filter '/api/' '/mempool/api/';
	sub_filter '/resources' '/mempool/resources';

	location /mempool/api/v1/ws {
		set $btcpay_route_upstream mempool_api;
		proxy_pass http://$btcpay_route_upstream:8999;
		proxy_redirect ~^http://mempool_api:8999(/.*)$ $1;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "Upgrade";
	}
	location /mempool/api/v1/ {
		set $btcpay_route_upstream mempool_api;
		rewrite ^/mempool/api/v1/(.*)$ /api/v1/$1 break;
		proxy_pass http://$btcpay_route_upstream:8999;
		proxy_redirect ~^http://mempool_api:8999/api/v1/(.*)$ /mempool/api/v1/$1;
	}
	location /mempool/api/ {
		set $btcpay_route_upstream mempool_api;
		rewrite ^/mempool/api/(.*)$ /api/v1/$1 break;
		proxy_pass http://$btcpay_route_upstream:8999;
		proxy_redirect ~^http://mempool_api:8999/api/v1/(.*)$ /mempool/api/$1;
	}
}
location ~ "^/([a-z]{2})/mempool(?:/(.*))?$" {
    rewrite "^/([a-z]{2})/mempool(?:/(.*))?$" $scheme://$server_name/mempool/$1/$2 redirect;
}
