location /spark/btc/ {
	set $btcpay_route_upstream clightning_bitcoin_spark;
	rewrite ^/spark/btc/(.*)$ /$1 break;
	proxy_pass http://$btcpay_route_upstream:9737;
	proxy_redirect ~^http://clightning_bitcoin_spark:9737/?(.*)$ /spark/btc/$1;
}
