location /sphinxrelay/ {
	set $btcpay_route_upstream sphinxrelay;
	rewrite ^/sphinxrelay/(.*)$ /$1 break;
	proxy_pass http://$btcpay_route_upstream:3300;
	proxy_redirect ~^http://sphinxrelay:3300/?(.*)$ /sphinxrelay/$1;
}
