location /sphinxrelay/ {
	set $btcpay_route_upstream sphinxrelay;
	rewrite ^/sphinxrelay/(.*)$ /$1 break;
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_pass http://$btcpay_route_upstream:3300;
	proxy_redirect ~^http://sphinxrelay:3300/?(.*)$ /sphinxrelay/$1;
}
