location /tallycoin-connect/ {
	set $btcpay_route_upstream tallycoin_connect;
	rewrite ^/tallycoin-connect/(.*)$ /$1 break;
	proxy_pass http://$btcpay_route_upstream:8123;
	proxy_redirect ~^http://tallycoin_connect:8123/?(.*)$ /tallycoin-connect/$1;
}
