location /tallycoin-connect/ {
	set $btcpay_route_upstream tallycoin_connect;
	rewrite ^/tallycoin-connect/(.*)$ /$1 break;
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_pass http://$btcpay_route_upstream:8123;
	proxy_redirect ~^http://tallycoin_connect:8123/?(.*)$ /tallycoin-connect/$1;
}
