#!/bin/bash

set -euo pipefail

repo_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
test_dir="$(mktemp -d)"
trap 'rm -rf "$test_dir"' EXIT

generator_dir="$test_dir/docker-compose-generator"
mkdir -p "$generator_dir" "$test_dir/Generated"
cp -a \
    "$repo_dir/docker-compose-generator/src" \
    "$repo_dir/docker-compose-generator/docker-fragments" \
    "$repo_dir/docker-compose-generator/crypto-definitions.json" \
    "$generator_dir/"
rm -rf "$generator_dir/src/bin" "$generator_dir/src/obj"

(
    cd "$generator_dir"
    BTCPAYGEN_REVERSEPROXY="nginx" \
    BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-add-cloudflared" \
    BTCPAYGEN_SUBNAME="fragment-exclusion-test" \
    dotnet run \
        --project src/docker-compose-generator.csproj \
        --configuration Release \
        --no-launch-profile \
        -p:TargetFrameworkOverride=net8.0
)

jq -e '
    (.fragments | index("opt-add-cloudflared") != null) and
    (.fragments | index("nginx") != null) and
    (.fragments | index("btcpay-host") != null) and
    (.fragments | index("nginx-https") == null)
' "$test_dir/Generated/manifest.json" >/dev/null
grep -q 'BTCPAY_BTCPAYHOSTENABLED' \
    "$test_dir/Generated/docker-compose.fragment-exclusion-test.yml"
grep -q 'btcpay_host_id_ed25519' \
    "$test_dir/Generated/docker-compose.fragment-exclusion-test.yml"

if grep -q "letsencrypt-nginx-proxy-companion" \
    "$test_dir/Generated/docker-compose.fragment-exclusion-test.yml"; then
    printf 'Excluded nginx-https services were generated\n' >&2
    exit 1
fi

(
    cd "$generator_dir"
    BTCPAYGEN_REVERSEPROXY="nginx" \
    BTCPAYGEN_EXCLUDE_FRAGMENTS="btcpay-host" \
    BTCPAYGEN_SUBNAME="recommended-exclusion-test" \
    dotnet run \
        --no-build \
        --project src/docker-compose-generator.csproj \
        --configuration Release \
        --no-launch-profile \
        -p:TargetFrameworkOverride=net8.0
)

jq -e '(.fragments | index("btcpay-host") == null)' \
    "$test_dir/Generated/manifest.json" >/dev/null
if grep -q 'BTCPAY_BTCPAYHOSTENABLED\|btcpay_host_id_ed25519' \
    "$test_dir/Generated/docker-compose.recommended-exclusion-test.yml"; then
    printf 'Excluded btcpay-host configuration was generated\n' >&2
    exit 1
fi

(
    cd "$generator_dir"
    BTCPAYGEN_CRYPTO1="btc" \
    BTCPAYGEN_REVERSEPROXY="nginx" \
    BTCPAYGEN_LIGHTNING="clightning" \
    BTCPAYGEN_ADDITIONAL_FRAGMENTS="" \
    BTCPAYGEN_SUBNAME="lightning-default-test" \
    dotnet run \
        --no-build \
        --project src/docker-compose-generator.csproj \
        --configuration Release \
        --no-launch-profile \
        -p:TargetFrameworkOverride=net8.0
)

jq -e '
    .requiredRoutes == [] and
    .secrets == [] and
    (.fragments | index("opt-add-rtl") == null) and
    (.fragments | index("opt-add-tor") == null)
' "$test_dir/Generated/manifest.json" >/dev/null
if grep -q 'bitcoin_rtl\|generated_tor_\|container_name: tor' \
    "$test_dir/Generated/docker-compose.lightning-default-test.yml"; then
    printf 'RTL or Tor configuration was generated by default\n' >&2
    exit 1
fi

(
    cd "$generator_dir"
    BTCPAYGEN_CRYPTO1="btc" \
    BTCPAYGEN_REVERSEPROXY="nginx" \
    BTCPAYGEN_LIGHTNING="clightning" \
    BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-add-rtl;opt-add-tor" \
    BTCPAYGEN_SUBNAME="clightning-rtl-tor-test" \
    dotnet run \
        --no-build \
        --project src/docker-compose-generator.csproj \
        --configuration Release \
        --no-launch-profile \
        -p:TargetFrameworkOverride=net8.0
)

jq -e '
    .requiredRoutes == ["rtl"] and
    .secrets == ["../secrets/tor_password"] and
    (.fragments | index("opt-add-rtl") != null) and
    (.fragments | index("opt-add-tor") != null)
' "$test_dir/Generated/manifest.json" >/dev/null
grep -q 'LN_IMPLEMENTATION: CLN' \
    "$test_dir/Generated/docker-compose.clightning-rtl-tor-test.yml"
docker compose \
    -f "$test_dir/Generated/docker-compose.clightning-rtl-tor-test.yml" \
    config --quiet

(
    cd "$generator_dir"
    BTCPAYGEN_CRYPTO1="btc" \
    BTCPAYGEN_REVERSEPROXY="nginx" \
    BTCPAYGEN_LIGHTNING="lnd" \
    BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-add-rtl" \
    BTCPAYGEN_SUBNAME="lnd-rtl-test" \
    dotnet run \
        --no-build \
        --project src/docker-compose-generator.csproj \
        --configuration Release \
        --no-launch-profile \
        -p:TargetFrameworkOverride=net8.0
)

jq -e '.requiredRoutes == ["rtl"]' \
    "$test_dir/Generated/manifest.json" >/dev/null
grep -q 'LND_SERVER_URL: http://lnd_bitcoin:8080/v1' \
    "$test_dir/Generated/docker-compose.lnd-rtl-test.yml"
docker compose \
    -f "$test_dir/Generated/docker-compose.lnd-rtl-test.yml" \
    config --quiet

(
    cd "$generator_dir"
    BTCPAYGEN_REVERSEPROXY="nginx" \
    BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-add-lightning-terminal" \
    BTCPAYGEN_SUBNAME="lit-secret-test" \
    dotnet run \
        --no-build \
        --project src/docker-compose-generator.csproj \
        --configuration Release \
        --no-launch-profile \
        -p:TargetFrameworkOverride=net8.0
)

jq -e '.secrets | index("../secrets/lit_password") != null' \
    "$test_dir/Generated/manifest.json" >/dev/null
grep -q -- '--uipassword_file=/run/secrets/lit_password' \
    "$test_dir/Generated/docker-compose.lit-secret-test.yml"
if grep -q -- '--uipassword=' \
    "$test_dir/Generated/docker-compose.lit-secret-test.yml"; then
    printf 'Lightning Terminal password was rendered into the command\n' >&2
    exit 1
fi

set +e
proxy_conflict_output="$({
    cd "$generator_dir" || exit 1
    BTCPAYGEN_REVERSEPROXY="none" \
    BTCPAYGEN_ADDITIONAL_FRAGMENTS="opt-add-cloudflared" \
    BTCPAYGEN_SUBNAME="fragment-requirement-test" \
    dotnet run \
        --no-build \
        --project src/docker-compose-generator.csproj \
        --configuration Release \
        --no-launch-profile \
        -p:TargetFrameworkOverride=net8.0
} 2>&1)"
proxy_conflict_status=$?
set -e

[ "$proxy_conflict_status" -eq 1 ]
[[ "$proxy_conflict_output" == *"group 'proxy'"* ]]

printf 'Docker Compose generator tests passed\n'
