entryPoints:
  http:
    address: :80
    http:
      redirections:
        entrypoint:
          to: https
          scheme: https
  https:
    address: :443
    http:
      tls:
        certResolver: default

providers:
  docker:
    exposedByDefault: false
    watch: true
    endpoint: unix:///var/run/docker.sock

# Enable only for debug
#api:
#  insecure: true
#  dashboard: true

log:
  level: ERROR # or DEBUG, PANIC, FATAL, WARN, and INFO

certificatesResolvers:
  default:
    acme:
      storage: /data/acme.json
      httpChallenge:
        entryPoint: http
